config/routes.rb
TodoList::Application.routes.draw do
  
  root to: 'home#index'
  get "home/index"

  devise_for :users, controllers: { registrations: "users" }  
  
  resources :lists do 
    collection do 
      post :reorder
    end
    resources :tasks, except: [:show, :index]  do 
      collection do 
        post :reorder
      end
    end
  end
    

   

 

  

end

app/models/list.rb
class List 
  
  include Mongoid::Document
  
  field :name_list, type: String
  # field :old_name, type: String
  field :date, type: DateTime, default: Time.now
  field :order,    type: Integer
  has_many :tasks, autosave: true
  belongs_to :user 

  validates :name_list, length: { minimum: 3 } 
  
  scope :all_sorted, -> { asc :order }

  scope :tasks_sorteds, -> { tasks.asc :order }
end

app/controllers/list_controller.rb
class ListController < ApplicationController
	def new
		@list = List.new
	end

	def edit
		begin
			@list = List.find(params[:id])
		rescue

		end
	end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to list_index_path
	rescue Mongoid::Errors::DocumentNotFound
		flash[:error] = "Lista não encontrada"
		redirect_to list_path
		#render text: "nao testado", status: 302
	end

	def show
		@list = List.find(params[:id])
	rescue StandardError
		redirect_to list_index_path
	end

	def index
		@lists = List.all.to_a

	end

	def create 
		# render text: params[:list].inspect
		#List.create(name_list:"Things to do", item1:"1", item2:"2", item3:"3")
		@list = List.create(list_params)

		if @list.persisted?
			flash[:notice] = 'Lista criada com sucesso'
			redirect_to list_path(@list.id)
		else
			flash.now[:error] =  'Não foi possível criar a lista'
			render :new			
		end
	end

	def update
		@list = List.find(params[:id])
		updated = @list.update_attributes(params[:list].permit(:name_list, :item1, :item2, :item3 ))
		if updated
			flash[:notice] = 'Lista atualizada com sucesso'
			redirect_to @list
		else
			flash.now[:error] =  'Não foi possível atualizar a lista'
			render :edit
		end
	end

	def list_params
		params.require(:list).permit(
			:name_list,
			:item1,
			:item2,
			:item3
			)
	end

end

app/controllers/lists_controller.rb
# encoding: UTF-8
class ListsController < ApplicationController
	def new
		@list = List.new
		@action = "Creating"
	end

	def edit
		begin
			@list = List.find(params[:id])
			@action = "Editing"
		rescue
			flash.now[:error] = "List não encontrada"
			render :edit
		end
	end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to lists_path
		rescue Mongoid::Errors::DocumentNotFound
			flash[:error] = "Lista não encontrada"
			redirect_to list_path
	end

	def show
		@list = List.find(params[:id])
		@tasks = @list.tasks.asc(:order).to_a
		rescue StandardError
			redirect_to lists_path
	end

	def index
		@lists = User.find_by(username: current_user.username).lists.to_a
		
		respond_to do |format|
			format.html 
			format.xml { render xml: @lists.to_xml }
			format.json { render json: @lists.to_json }
		end
	end

	def create 
		@list         = List.new(list_params)
		@list.user_id = current_user.id
		
		if @list.save
			flash[:notice] = 'Lista criada com sucesso'
			redirect_to list_path(@list.id)
		else
			flash.now[:error] =  'Não foi possível criar a lista'
			render :new			
		end
	end

	def update
		@list = List.find(params[:id])
		updated = @list.update_attributes(params[:list].permit(:name_list, :item1, :item2, :item3 ))
		if updated
			flash[:notice] = 'Lista atualizada com sucesso'
			redirect_to @list
		else
			flash.now[:error] =  'Não foi possível atualizar a lista'
			render :edit
		end
	end

	def list_params
		params.require(:list).permit(
			:name_list
		)
	end

	def reorder
		@ids = params[:ids]
		
		@ids.each_with_index do |id, index|
			list = List.find(id)
			list.order = index
			list.save
		end
		
		render text: "Ok", status: 200 # :index
	end
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/lists/edit.html.erb
<%= render "shared/form_list" %>

app/views/lists/index.html.erb
 
<ul id="lists" class="unstyled sort lists-container"  >
  <% @lists.each do |list| %>
  <li data-id="<%= list.id %>">
    <strong><%= list.name_list  %></strong>
    <span class="actions">
      <%= link_to 'Show', list_path(list) %><span class="dot">&middot;</span>
      <%= link_to 'Edit', edit_list_path(list) %><span class="dot">&middot;</span>
      <%= link_to 'Destroy', list, :confirm => 'Are you sure?', :method => :delete %>
    </span>
  </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= render "shared/form_list" %>

app/views/lists/show.html.erb
<p>
  <strong>Name list:</strong>
  <%= @list.name_list %>
</p>
<p>
  <strong>Tasks:</strong><br>
  <ul class="unstyled sort tasks-container" id="tasks" data-list-id="<%= @list.id %>">
    <%= render partial: "shared/task", collection: @tasks %>
  </ul>
</p>
<br>
<%= link_to 'Back', lists_path %>
| <%= link_to 'Edit list', edit_list_path(@list) %> 
<!-- O link_to só aceita paths como parâmetros e caso os paths precisem de parâmetros devem ser passados como abaixo seprados por vírgulas -->
| <%= link_to 'New Task', new_list_task_path(@list) %>