config/routes.rb
TodoList::Application.routes.draw do
  
  root to: 'home#index'
  get "home/index"

  devise_for :users, controllers: { registrations: "users" }  
  
  resources :lists do 
    collection do 
      post :reorder
    end
    resources :tasks, except: [:show, :index]  do 
      collection do 
        post :reorder
      end
    end
  end
    

   

 

  

end

app/views/shared/_form.html.erb
<%= form_for @list do |f| %>

  <% if @list.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@list.errors.count, "error") %> 
        prohibited this list from being saved:
      </h2>

      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name_list %><br>
    <%= f.text_field :name_list %><br>
  </p>
 
  <p>
    <%= f.label :item1 %><br>
    <%= f.text_field :item1 %><br>
    <%= f.label :item2 %><br>
    <%= f.text_field :item2 %><br>
    <%= f.label :item3 %><br>
    <%= f.text_field :item3 %>
  </p>
 
  <p>
    <%= f.submit :save_list %>
  </p>
<% end %>

<%= link_to 'Back', lists_path %>

app/views/shared/_form_list.html.erb
<%= form_for @list, :html => { :id => "form-list" } do |f| %>

  <h1> <%= @action %> a list</h1> 

  <% if @list.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@list.errors.count, "error") %> 
        prohibited this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    
    <%= f.text_field :name_list, autofocus: true, :placeholder => "Name list" %>
    <div>
      <%= f.submit :Save, :class => "btn btn-large btn-primary" %>
    </div>
  </p>
  <%= link_to 'Back', lists_path %>
<% end %>

app/views/shared/_form_task.html.erb
<%= form_for [@list, @task], :html => { :id => "form-task" } do |f| %>
  <h1>New Task for <%= @list.name_list %> </h1>

  <% if @task.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@task.errors.count, "error") %> 
        prohibited this list from being saved:
      </h2>

      <ul>
        <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= hidden_field_tag "task[list_id]", @list.id %>
    <%= f.check_box :status %>
    <%= f.text_field :body, placeholder: "Tell me your task", autofocus: true %>
  </p>

  <p>
    <div>
      <%= f.submit :Save, :class => "btn btn-large btn-primary" %>
    </div>
  </p>
  <%= link_to 'Back', lists_path %>
<% end %>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/shared/_task.html.erb
<li data-id="<%= task.id %>" >
  <%= check_box_tag 'status', task.status, task.status, {disabled: true} %> 
  <%# <%= link_to edit_list_task_path(@list, @task) do  %>
  <%#   Sempre que tive mais de uma parametros é bom passa-los explicitamente %>
  <%= link_to edit_list_task_path(list_id: @list.id, id: task.id) do  %>
    <%= task.body %>
  <% end %>

  <%= link_to 'X', 
    [task.list, task], 
    :confirm => 'Are you sure?', 
    :method => :delete, 
    class: "destroy_task" 
  %>
</li>