config/routes.rb
TodoList::Application.routes.draw do
  
  root to: 'home#index'
  get "home/index"

  devise_for :users, controllers: { registrations: "users" }  
  
  resources :lists do 
    collection do 
      post :reorder
    end
    resources :tasks, except: [:show, :index]  do 
      collection do 
        post :reorder
      end
    end
  end
    

   

 

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mTodo List</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <% if user_signed_in? %>
            <%= link_to "mTodo List", lists_path , class: "brand" %>
          <% else %>
            <%= link_to "mTodo List", root_path , class: "brand" %>
          <% end %>
          <ul class="nav"> 
            <% if user_signed_in? %>
              <li><%= link_to 'New list', new_list_path %></li>
            <% end -%>
          </ul>
          <ul id="login" class ="nav">
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
              </li>
            <% else %>
              <li>
              <%= link_to "Login", new_user_session_path  %>
              </li>
            <% end %>
          </ul>

          <ul id="signup" class="nav">
            <% if user_signed_in? %>
              <li>
              <%= link_to(current_user.username, edit_user_registration_path) %>
              </li>
            <% else %>
              <li>
              <%= link_to('Sign up', new_user_registration_path)  %>
              </li>
            <% end %>
          </ul>

        </div>
      </div> 
    </header>

    <%- flash.each do |key, msg| -%>
      <div id="<%= key %>">
        <p style="float:right;"><%= link_to_function 'X', "Effect.Fade('#{key}')" %></p>
        <p><%= msg %></p>
        <div class="clear"></div>
      </div>
    <%- end -%>

    <div class="content">
      <%= yield %>
    </div>

    <hr>
    <footer>
        <p>&copy; <a href="https://github.com/fmoraisrj" > Felipe de Morais </a> </p>
      </footer>
  </div>
</body>
</html>